# Generated by Django 5.1.7 on 2025-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], max_length=10)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
