# Generated by Django 5.1.7 on 2025-03-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_accessories_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='not_accessories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='accessories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('children', 'Children'), ('men', 'Men'), ('women', 'Women')], max_length=10),
        ),
    ]
