# Generated by Django 5.1.7 on 2025-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_not_accessories_alter_product_accessories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='accessories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='not_accessories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
